/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author LENOVO
 */
public class carts extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.Koneksi.Koneksi();
    
    public void judul() {
        
        Object[] judul = {
            "Name", "Phone", "Address", "Type", "Color", "Price", "Quantity", "Subtotal", "Total", "Pay", "Outcome", "Date"
        };
        tabModel = new DefaultTableModel(null, judul);
        tableCart.setModel(tabModel);
    }
    
    public void tampilData(String where) {
        
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM cart " + where);

            while (rs.next()) {
                Object[] data = {
                    rs.getString("Name"),
                    rs.getString("Phone"),
                    rs.getString("Address"),
                    rs.getString("Type"),
                    rs.getString("Color"),
                    rs.getString("Price"),
                    rs.getString("Quantity"),
                    rs.getString("Subtotal"),
                    rs.getString("Total"),
                    rs.getString("Pay"),
                    rs.getString("Outcome"),
                    rs.getString("Date"),
                    
                };

                tabModel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void total(){
        
        int total = 0;
        for (int i = 0; i < tableCart.getRowCount(); i++){
            int amount = Integer.parseInt((String)tableCart.getValueAt(i, 7));
            total += amount;
        }
        txtTotal.setText("" + total);
    }
    
    public void pay(){
        
        int total = Integer.parseInt(txtTotal.getText());
        int pay = Integer.parseInt(txtPay.getText());

        if (pay < total) {
            JOptionPane.showMessageDialog(null, "The payment amount must be greater than the total price!");
            txtPay.setText("");
        } else {
            int change = pay - total;
            txtOutcome.setText(Integer.toString(change));
        }
    }
    
    public void date(){
        // Mendapatkan tanggal saat ini
        Date currentDate = new Date();

        // Mengatur format tanggal yang diinginkan (misalnya: "dd-MM-yyyy HH:mm:ss")
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

        // Mengisi nilai tanggal ke dalam JTextField dengan nama txtDate
        txtDate.setText(dateFormat.format(currentDate));
    }

    /**
     * Creates new form carts
     */
    public carts() {
        
        initComponents();
        judul();
        tampilData("");
        total();
        date();
        setLocationRelativeTo(this);
        btnBack.setEnabled(false);
        btnPrint.setEnabled(false);
        btnInsert.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        txtPhone = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        txtOutcome = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCart.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 780, 180));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 0));
        btnUpdate.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 95, 40));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 95, 40));

        btnPrint.setBackground(new java.awt.Color(0, 0, 255));
        btnPrint.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        txtPhone.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 10, -1));

        txtName.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 10, -1));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 30, 20));
        getContentPane().add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 10, -1));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 10, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 10, -1));
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 10, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel6.setText("Change :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, 20));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel7.setText("*After calculating, please click the last row before clicking the 'Insert payment data at last row' button");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 600, 20));

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel8.setText("Pay :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, 20));

        txtPay.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 110, 30));

        txtOutcome.setEditable(false);
        txtOutcome.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtOutcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 110, 30));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 110, 30));

        btnCalculate.setBackground(new java.awt.Color(255, 153, 0));
        btnCalculate.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 110, -1));

        btnInsert.setBackground(new java.awt.Color(255, 153, 0));
        btnInsert.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("Insert payment data at last row");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 250, -1));

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel9.setText("Total :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 40, 20));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 10, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carts.png"))); // NOI18N
        jLabel2.setText(" Cart");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        btnBack.setBackground(new java.awt.Color(255, 153, 0));
        btnBack.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 87));

        jLabel1.setText("            ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 780, -1));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCartMouseClicked

        txtName.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 0).toString());
        txtPhone.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 1).toString());
        txtAddress.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 2).toString());
        txtType.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 3).toString());
        txtColor.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 4).toString());
        txtPrice.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 5).toString());
        txtQuantity.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 6).toString());
        txtSubtotal.setText(tableCart.getValueAt(tableCart.getSelectedRow(), 7).toString());
        btnInsert.setEnabled(true);

    }//GEN-LAST:event_tableCartMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        JFrame transaction = new transaction();
        this.setVisible(false);
        transaction.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {
            int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Are you sure want to delete?", "Information", JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM cart WHERE color='" + tabModel.getValueAt(tableCart.getSelectedRow(), 4) + "'");
                tampilData("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        total();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        try {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Vesmart\\src\\view\\reportreceipt.jrxml");
            String query = "SELECT * FROM cart";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);

            jdesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, cn);
            JasperViewer.viewReport(jprint, rootPaneCheckingEnabled, Locale.FRENCH);
        } catch(Exception e) {
            e.printStackTrace();}
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        pay();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        try {
            st = cn.createStatement();
            String name = txtName.getText();
            String phone = txtPhone.getText();
            String address = txtAddress.getText();
            String type = txtType.getText();
            String color = txtColor.getText();
            String price = txtPrice.getText();
            String quantity = txtQuantity.getText();
            String subtotal = txtSubtotal.getText();
            String total = txtTotal.getText();
            String pay = txtPay.getText();
            String outcome = txtOutcome.getText();
            String date = txtDate.getText();

            String updateQuery = "UPDATE cart SET "
            + "total='" + total + "', "
            + "pay='" + pay + "', "
            + "date='" + date + "', "
            + "outcome='" + outcome + "'WHERE color='" + color + "'";

            st.executeUpdate(updateQuery);

            tampilData("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnBack.setEnabled(true);
        btnPrint.setEnabled(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        try {
            int jawab;
            {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM cart");
                tampilData("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrame dashboard = new dashboard();
        this.setVisible(false);
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCart;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOutcome;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
